### ISSUE TITLE
Auch ein spannendes Thema

### ISSUE THREAD

**Issue by Katja1510** [StephanieRehwald2/wmp-t9-1#1]
Hallo Stephanie,
das Thema enthält ebenfalls viel Potential, um IT-Optimierungen durchzuführen - sehr spannend. Mir sind nur ein paar kleine Flüchtigkeitsfehler aufgefallen, die ich im nächsten Issue schreibe.

**Comment by StephanieRehwald2** [comment]
Danke :) ich arbeite es aus!
