### ISSUE TITLE
Kleine Anmerkungen

### ISSUE THREAD

**Issue by Katja1510** [StephanieRehwald2/wmp-t9-1#2]
Zeile 5 Nachverfolgung
Zeile 6 Dateien
Zeile 6 In den folgenden drei 
Zeile 10 Fragekataloge
Zeile 11 unterscheiden sich sowohl 
Zeile 11 Fachdisziplin
Zeile 13 innerhalb

Ich hoffe, die Zeilen stimmen in deiner Raw-Version auch noch :).
Ich würde vielleicht noch erklären, was Elektronische Laborbücher sind. Der Begriff ist mir gänzlich unbekannt.
Liebe Grüße und bis bald
Katja

**Comment by StephanieRehwald2** [comment]
Vielen Dank für die Korrekturen!
