### ISSUE TITLE
Wenn Änderungen kommen, einfach schreiben

### ISSUE THREAD

**Issue by Katja1510** [StephanieRehwald2/wmp-t9-1#4]
Wie gerade schon in der Mail geschrieben: Wenn ich noch deine Überarbeitung lesen soll, gib einfach Bescheid - ich habe am Sonntag während der Fahrt nach Bremen und zurück Zeit. Ich bin Beifahrer :D. 
Wie gesagt, das Thema finde ich sehr interessant und ich würde gerne mehr lesen 👍 !
Liebe Grüße
Katja

**Comment by StephanieRehwald2** [comment]
Vielen Dank für das Angebot! ...ich bin nur leider auf die letzte Minute...
Aber wir können uns gerne auch nach Deadline noch austauschen! ich bin auch gespannt, was bei dir herauskommt!

**Comment by Katja1510** [comment]
Ich habe es gestern leider nicht mehr gesehen - erst jetzt. Aber wie du schon geschrieben hast, können wir uns gerne noch mal austauschen :)
LG, Katja
